### ISSUE TITLE
Issue with reading key file

### ISSUE THREAD

**Issue by bassemaziz** [burhan/pyipay#2]
* ipaypipe version:
* Python version:3.7
* Operating System:Linux Ubuntu 

### Description
BadKeystoreFormatException
Not a JKS or JCEKS keystore (magic number wrong; expected FEEDFEED or CECECECE)
i got that error  
Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by burhan** [comment]
Hey, if you are still facing this issue - please re-open.

**Comment by khaled-s** [comment]
Hello,
I'm getting the same problem
